steps:
  # Install functions dependencies
  - name: 'node:20'
    dir: 'functions'
    entrypoint: 'npm'
    args: ['ci']

  # Build functions (TypeScript to JavaScript)
  - name: 'node:20'
    dir: 'functions'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Deploy functions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy contact \
          --gen2 \
          --runtime=nodejs20 \
          --region=asia-northeast1 \
          --source=functions \
          --entry-point=contact \
          --trigger-http \
          --allow-unauthenticated \
          --set-env-vars="SMTP_HOST=$$SMTP_HOST,SMTP_PORT=$$SMTP_PORT,SMTP_SECURE=$$SMTP_SECURE,SMTP_USER=$$SMTP_USER,SMTP_PASSWORD=$$SMTP_PASSWORD,SMTP_FROM=$$SMTP_FROM,CONTACT_EMAIL=$$CONTACT_EMAIL"
    secretEnv:
      - 'SMTP_HOST'
      - 'SMTP_PORT'
      - 'SMTP_SECURE'
      - 'SMTP_USER'
      - 'SMTP_PASSWORD'
      - 'SMTP_FROM'
      - 'CONTACT_EMAIL'

  # Build Next.js static export
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']

  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Deploy to Firebase Hosting
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm install -g firebase-tools && firebase deploy --only hosting --project=fractal-hokan-funabashi'

availableSecrets:
  secretManager:
    - versionName: projects/fractal-hokan-funabashi/secrets/SMTP_HOST/versions/latest
      env: 'SMTP_HOST'
    - versionName: projects/fractal-hokan-funabashi/secrets/SMTP_PORT/versions/latest
      env: 'SMTP_PORT'
    - versionName: projects/fractal-hokan-funabashi/secrets/SMTP_SECURE/versions/latest
      env: 'SMTP_SECURE'
    - versionName: projects/fractal-hokan-funabashi/secrets/SMTP_USER/versions/latest
      env: 'SMTP_USER'
    - versionName: projects/fractal-hokan-funabashi/secrets/SMTP_PASSWORD/versions/latest
      env: 'SMTP_PASSWORD'
    - versionName: projects/fractal-hokan-funabashi/secrets/SMTP_FROM/versions/latest
      env: 'SMTP_FROM'
    - versionName: projects/fractal-hokan-funabashi/secrets/CONTACT_EMAIL/versions/latest
      env: 'CONTACT_EMAIL'

options:
  logging: CLOUD_LOGGING_ONLY
